// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Utilities from "../Utilities.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function parse(line) {
  var firstNumber = {
    contents: undefined
  };
  var lastNumber = {
    contents: undefined
  };
  var line$1 = line.trim();
  if (line$1 === "") {
    return 0;
  }
  line$1.split("").forEach(function ($$char) {
        if ($$char === "0" || $$char === "1" || $$char === "2" || $$char === "3" || $$char === "4" || $$char === "5" || $$char === "6" || $$char === "7" || $$char === "8" || $$char === "9") {
          if (Belt_Option.isNone(firstNumber.contents)) {
            firstNumber.contents = $$char;
          }
          lastNumber.contents = $$char;
          return ;
        }
        
      });
  var match = firstNumber.contents;
  var match$1 = lastNumber.contents;
  if (match !== undefined && match$1 !== undefined) {
    return Belt_Option.getExn(Belt_Int.fromString("" + match + "" + match$1 + ""));
  }
  console.log("Failed to parse line: " + line$1 + "");
  return 0;
}

function sum(input) {
  return input.split("\n").map(parse).reduce((function (sum, n) {
                return sum + n | 0;
              }), 0);
}

console.log(sum(Utilities.input));

var input = Utilities.input;

var input2 = "1abc2\npqr3stu8vwx\na1b2c3d4e5f\ntreb7uchet";

export {
  input ,
  input2 ,
  parse ,
  sum ,
}
/*  Not a pure module */
