// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utilities from "../Utilities.bs.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var InvalidInput = /* @__PURE__ */Caml_exceptions.create("DaySixPartTwo.InvalidInput");

var match = Utilities.input.split("\n").filter(function (line) {
        return line.trim().length > 0;
      }).map(function (data) {
      return Belt_Option.getExn(Belt_Float.fromString(Caml_array.get(data.split(":"), 1).trim().replace(/\D/g, "")));
    });

if (match.length !== 2) {
  throw {
        RE_EXN_ID: InvalidInput,
        _1: "The input was invalid.",
        Error: new Error()
      };
}

var time = match[0];

var distance = match[1];

var race_time = time | 0;

var race = {
  time: race_time,
  distance: distance
};

var distances = [];

for(var t = race_time - 1 | 0; t >= 1; --t){
  var speed = race_time - t | 0;
  distances.push(speed * t);
}

console.log(distances.filter(function (distance$1) {
          return distance$1 > distance;
        }).length);

var input = Utilities.input;

var input2 = "Time:      7  15   30\nDistance:  9  40  200\n";

export {
  input ,
  input2 ,
  InvalidInput ,
  race ,
  distances ,
}
/* match Not a pure module */
