// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Nodefs from "node:fs";
import * as Process from "process";

var input = Nodefs.readFileSync("" + Path.dirname(Process.argv[1]) + "/input.txt", "utf8");

export {
  input ,
}
/* input Not a pure module */
